name: build

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
      - 'composer.json'
      - 'phpunit.*.dist'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

jobs:
  tests:
    name: Redis ${{ matrix.redis }}
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    strategy:
      matrix:
        redis:
          - 4
          - 5
          - 6
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      os: '["ubuntu-latest"]'
      php: '["7.4", "8.0", "8.1"]'
      phpunitConfig: phpunit.redis-${{ matrix.redis }}.xml.dist
