name: mutation test

on:
  pull_request:
    paths: &paths
      - '.github/workflows/mutation.yml'
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'infection.json.dist'
      - 'phpunit.*.dist'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

jobs:
  mutation:
    uses: yiisoft/actions/.github/workflows/roave-infection.yml@master
    with:
      bin-name: ../../bin/roave-infection-with-redis
      ini-values: memory_limit=-1
      os: '["ubuntu-latest"]'
      php: '["8.1"]'
      threads: '1'
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
